post_it/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'home/about'
  get 'home/contact'
  get 'home/faq'

end

post_it/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

post_it/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

post_it/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
	devise_parameter_sanitizer.for(:sign_up) << :name
	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

post_it/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end
end

post_it/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index, :show] 
  before_action :correct_user, only: [:edit, :update, :destroy] 

  respond_to :html

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :name)
    end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
  end
end

post_it/app/helpers/application_helper.rb
module ApplicationHelper
end

post_it/app/helpers/home_helper.rb
module HomeHelper
end

post_it/app/helpers/posts_helper.rb
module PostsHelper
end

post_it/app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Post_It.', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', home_about_path %></li>
            <li><%= link_to 'FAQ', home_faq_path %></li>
            <li><%= link_to 'Contact', home_contact_path %></li>

            <% if user_signed_in? %>
            	<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            	<li><%= link_to 'Add Post', new_post_path %></li>
            	<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
            	<li><%= link_to 'Login', new_user_session_path %></li>
            	<li><%= link_to 'Join', new_user_registration_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

post_it/app/views/home/about.html.erb
<h1> About me...</h1>
<p> My name is Tyler and I'm building a pinterest-like site. </p>

<p> to be continued... </p>

post_it/app/views/home/contact.html.erb
<h1> Contact </h1>

<p> to be continued... </p>

post_it/app/views/home/faq.html.erb
<h1> FAQ </h1>

<p> to be continued... </p>

post_it/app/views/home/index.html.erb
<div class="jumbotron">
		<h1>Hello World</h1>
		<p>Welcome to Post_It.</p>
</div>

post_it/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= render 'home/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

post_it/app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

post_it/app/views/posts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing Post</h1></div>
  <div class="panel-body">

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

post_it/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading"><h1><center>Welcome to Post_It. </br> Just Post_It.</center></h1></div>
</div>
</br>

 <div class="container">
    <% @posts.each do |post| %>
    <div class="col-md-4 box-">
        <center><%= link_to image_tag(post.image.url(:medium)), post %></br>
        <%= post.description %></br>
        <strong><%= post.user.name if post.user %></strong><br/>
        <% if post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></center></br>
        <% end %>
    </div>
    <% end %> 
</div>
      

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

post_it/app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>New Post</h1></div>
  <div class="panel-body">

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

post_it/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-offset-2 col-md-8">

<div class="panel panel-primary">
  <div class="panel-heading center">
  	<center><%= image_tag @post.image.url(:large) %></center></div>
  <div class="panel-body panel-custom">

		<center><%= @post.description %></br>
		<strong><%= @post.user.name %></strong><br/>

		<% if @post.user == current_user %>
			<%= link_to 'Edit', edit_post_path(@post) %>
		<% end %>
		<%= link_to 'Back', posts_path %></center>
	</div>
  </div>
 </div>
</div>